[profile.default]
src = "src"
out = "out"
libs = ["lib"]

# Etherscan API key for verification
etherscan_api_key = "${ETHERSCAN_API_KEY}"

[rpc_endpoints]
base_sepolia = "https://sepolia.base.org"

[etherscan]
base-sepolia = { key = "${ETHERSCAN_API_KEY}" }