[profile.default]
src = '.'
out = 'out'
libs = ['lib']
solc = "0.8.20"
optimizer = true
optimizer_runs = 200
via_ir = true
skip = ["lib/**/certora/**/*"]

[rpc_endpoints]
base_sepolia = "https://sepolia.base.org"