[profile.default]
src = "src"
out = "out"
libs = ["lib"]

# Etherscan API key for verification
etherscan_api_key = "${ETHERSCAN_API_KEY}"

[rpc_endpoints]
base_sepolia = "https://sepolia.base.org"
optimism_sepolia = "https://sepolia.optimism.io"
base_mainnet = "https://mainnet.base.org"

[etherscan]
base-sepolia = { key = "${ETHERSCAN_API_KEY}" }
optimism-sepolia = { key = "${ETHERSCAN_API_KEY}" }
base = { key = "${ETHERSCAN_API_KEY}" }